version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tienda
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tienda_net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - tienda_net

  backend:
    build: ./backend
    expose:
    - "8000"
    # opcionalmente para debug:
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/tienda
    depends_on:
      - db
    networks:
      - tienda_net

  frontend:
    build: ./frontend
    expose:
      - "80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - tienda_net

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAINS: >
        mitiendaproyecto.zapto.org -> http://frontend:80
      STAGE: 'production'
    volumes:
      - ssl_certs_data:/var/lib/https-portal
    depends_on:
      - frontend
    restart: always
    networks:
      - tienda_net



volumes:
  postgres_data:
  ssl_certs_data:

networks:
  tienda_net:
